spring:
  application:
    name: pro
  datasource:
    url: jdbc:postgresql://localhost:5432/demopost?currentSchema=public
    username: shiv
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
