name: Java CI - Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    # Expose Spring Boot config to the Gradle test JVM via env vars (recommended)
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/bookdb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_PROFILES_ACTIVE: test

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: bookdb
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U test -d bookdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to be ready..."
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U test > /dev/null 2>&1; then
              echo "Postgres is ready"
              break
            fi
            # fallback: check port open (runner usually has /dev/tcp)
            if (echo > /dev/tcp/localhost/5432) >/dev/null 2>&1; then
              echo "Postgres port open (pg_isready not available)."
              break
            fi
            sleep 2
          done
        env:
          PGPASSWORD: test

      - name: Build and run tests (Gradle)
        run: ./gradlew clean build --no-daemon --info
        env:
          # re-affirm important env to Gradle JVM (optional, they inherit job env)
          SPRING_DATASOURCE_URL: ${{ env.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ env.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.SPRING_DATASOURCE_PASSWORD }}
          SPRING_JPA_DATABASE_PLATFORM: ${{ env.SPRING_JPA_DATABASE_PLATFORM }}
          SPRING_PROFILES_ACTIVE: ${{ env.SPRING_PROFILES_ACTIVE }}
